# coding: utf-8

"""
    LOD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.authority_search_api import AuthoritySearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthoritySearchApi(unittest.TestCase):
    """AuthoritySearchApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.authority_search_api.AuthoritySearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_record_by_authority_id(self):
        """Test case for get_record_by_authority_id

        search for an given ID of a given authority-provider  # noqa: E501
        """
        pass

    def test_get_record_by_authority_id_and_entity_id(self):
        """Test case for get_record_by_authority_id_and_entity_id

        search for an given ID of a given authority-provider on a given entity-index  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
