# coding: utf-8

"""
    LOD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reconcile_api import ReconcileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReconcileApi(unittest.TestCase):
    """ReconcileApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.reconcile_api.ReconcileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_open_refine_reconcilation_service_api__httpsgithub_com_open_refine_open_refinewiki_reconciliation_service_api(self):
        """Test case for open_refine_reconcilation_service_api__httpsgithub_com_open_refine_open_refinewiki_reconciliation_service_api

        OpenRefine Reconcilation Service API  # noqa: E501
        """
        pass

    def test_openrefine_data_extension_api_httpsgithub_com_open_refine_open_refinewiki_data_extension_api(self):
        """Test case for openrefine_data_extension_api_httpsgithub_com_open_refine_open_refinewiki_data_extension_api

        Openrefine Data-Extension-API  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_flyout_entity_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api(self):
        """Test case for openrefine_suggest_api_flyout_entity_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_flyout_property_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api(self):
        """Test case for openrefine_suggest_api_flyout_property_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_flyout_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api(self):
        """Test case for openrefine_suggest_api_flyout_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_suggest_entity_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api(self):
        """Test case for openrefine_suggest_api_suggest_entity_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_suggest_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api(self):
        """Test case for openrefine_suggest_api_suggest_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_openrefine_suggest_api_suggest_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api_0(self):
        """Test case for openrefine_suggest_api_suggest_type_entry_point__httpsgithub_com_open_refine_open_refinewiki_suggest_api_0

        Openrefine Suggest-API suggest Entry Point  # noqa: E501
        """
        pass

    def test_post_api_data(self):
        """Test case for post_api_data

        OpenRefine Reconcilation Service API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
