# coding: utf-8

"""
    LOD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_and_access_api import SearchAndAccessApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchAndAccessApi(unittest.TestCase):
    """SearchAndAccessApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.search_and_access_api.SearchAndAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_document_out_of_an_entity_type(self):
        """Test case for get_document_out_of_an_entity_type

        get a single record of an entity-index, or search for all records containing this record as an attribute via isAttr parameter  # noqa: E501
        """
        pass

    def test_search_in_index(self):
        """Test case for search_in_index

        search on one given entity-index  # noqa: E501
        """
        pass

    def test_search_over_all_indices(self):
        """Test case for search_over_all_indices

        search over all entity-indices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
