# coding: utf-8

"""
    LOD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.explorative_search_api import ExplorativeSearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExplorativeSearchApi(unittest.TestCase):
    """ExplorativeSearchApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.explorative_search_api.ExplorativeSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_aggregate_top_authors_date_published_and_related_topics_around_topics(self):
        """Test case for aggregate_top_authors_date_published_and_related_topics_around_topics

        aggregate topAuthors, datePublished and relatedTopics around topics  # noqa: E501
        """
        pass

    def test_correlate_topics_with_their_mutual_occurances(self):
        """Test case for correlate_topics_with_their_mutual_occurances

        correlate topics with their mutual occurances  # noqa: E501
        """
        pass

    def test_query_topics(self):
        """Test case for query_topics

        perform a simple serach on the topics index  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
