# coding: utf-8

"""
    LOD API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.source_api import SourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSourceApi(unittest.TestCase):
    """SourceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.source_api.SourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_source_record_by_entity_and_entity_id(self):
        """Test case for get_source_record_by_entity_and_entity_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
